"""add required_skills to company

Revision ID: 669c27a218dc
Revises: bb2686c763ec
Create Date: 2026-07-06 16:40:07.192003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669c27a218dc'
down_revision = 'bb2686c763ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_skills', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('required_skills')

    # ### end Alembic commands ###
