"""inital migration

Revision ID: 6ba76fbc061e
Revises: 
Create Date: 2026-07-02 12:21:13.463541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba76fbc061e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgpa_criteria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tenth_criteria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('twelfth_criteria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('backlog_allowed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('eligibility_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('eligibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligibility', sa.TEXT(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('eligibility_notes')
        batch_op.drop_column('backlog_allowed')
        batch_op.drop_column('twelfth_criteria')
        batch_op.drop_column('tenth_criteria')
        batch_op.drop_column('cgpa_criteria')

    # ### end Alembic commands ###
